# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='users',
            name='info',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='info'),
        ),
        migrations.AddField(
            model_name='users',
            name='nick',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='nick'),
        ),
        migrations.AlterField(
            model_name='users',
            name='openid',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='openid'),
        ),
    ]
